app = "guessthe-backend"
primary_region = "gru" # 🇧🇷 Muda para São Paulo (Latência cai de 150ms para ~30ms)

[http_service]
  internal_port = 8080
  force_https = true
  
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  
  processes = [ "app" ]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb" 